include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Downgrade errors to warnings for CI
    missing_required_argument: warning
    deprecated_member_use: ignore
    avoid_print: ignore
    invalid_use_of_internal_member: ignore
    depend_on_referenced_packages: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
