// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/unit/services/recurring_todo_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:todo_app/core/errors/failures.dart' as _i5;
import 'package:todo_app/domain/entities/todo.dart' as _i6;
import 'package:todo_app/domain/repositories/todo_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Todo>>>(
                    this,
                    Invocation.method(#getTodos, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>> getFilteredTodos(
    String? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredTodos, [filter]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Todo>>>(
                    this,
                    Invocation.method(#getFilteredTodos, [filter]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Todo>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Todo>> getTodoById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Todo>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Todo>>(
                this,
                Invocation.method(#getTodoById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Todo>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> createTodo(
    String? title,
    String? description,
    DateTime? dueDate, {
    int? categoryId,
    DateTime? notificationTime,
    String? recurrenceRule,
    int? parentRecurringTodoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createTodo,
              [title, description, dueDate],
              {
                #categoryId: categoryId,
                #notificationTime: notificationTime,
                #recurrenceRule: recurrenceRule,
                #parentRecurringTodoId: parentRecurringTodoId,
              },
            ),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(
                  #createTodo,
                  [title, description, dueDate],
                  {
                    #categoryId: categoryId,
                    #notificationTime: notificationTime,
                    #recurrenceRule: recurrenceRule,
                    #parentRecurringTodoId: parentRecurringTodoId,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> updateTodo(_i6.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#updateTodo, [todo]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> toggleCompletion(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCompletion, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#toggleCompletion, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
