// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/unit/providers/category_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:todo_app/core/errors/failures.dart' as _i5;
import 'package:todo_app/domain/entities/category.dart' as _i6;
import 'package:todo_app/domain/entities/todo.dart' as _i8;
import 'package:todo_app/domain/repositories/category_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Category>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Category>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Category>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Category>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Category>> getCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.Category>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Category>>(
                    this,
                    Invocation.method(#getCategoryById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Category>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> createCategory(
    String? userId,
    String? name,
    String? color,
    String? icon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [userId, name, color, icon]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#createCategory, [userId, name, color, icon]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> updateCategory(
    _i6.Category? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#updateCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#deleteCategory, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Todo>>> getTodosByCategory(
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosByCategory, [categoryId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.Todo>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.Todo>>>(
                    this,
                    Invocation.method(#getTodosByCategory, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Todo>>>);
}
