// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/integration/todo_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i10;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:todo_app/core/errors/failures.dart' as _i6;
import 'package:todo_app/core/services/notification_service.dart' as _i9;
import 'package:todo_app/core/services/recurring_todo_service.dart' as _i11;
import 'package:todo_app/core/utils/clock.dart' as _i3;
import 'package:todo_app/domain/entities/todo.dart' as _i7;
import 'package:todo_app/domain/repositories/todo_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoRepository_0 extends _i1.SmartFake
    implements _i2.TodoRepository {
  _FakeTodoRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClock_1 extends _i1.SmartFake implements _i3.Clock {
  _FakeClock_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Todo>>>(
                    this,
                    Invocation.method(#getTodos, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>> getFilteredTodos(
    String? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredTodos, [filter]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Todo>>>(
                    this,
                    Invocation.method(#getFilteredTodos, [filter]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>> searchTodos(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTodos, [query]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Todo>>>(
                    this,
                    Invocation.method(#searchTodos, [query]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Todo>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Todo>> getTodoById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Todo>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i7.Todo>>(
                this,
                Invocation.method(#getTodoById, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Todo>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, int>> createTodo(
    String? title,
    String? description,
    DateTime? dueDate, {
    int? categoryId,
    DateTime? notificationTime,
    String? recurrenceRule,
    int? parentRecurringTodoId,
    double? locationLatitude,
    double? locationLongitude,
    String? locationName,
    double? locationRadius,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createTodo,
              [title, description, dueDate],
              {
                #categoryId: categoryId,
                #notificationTime: notificationTime,
                #recurrenceRule: recurrenceRule,
                #parentRecurringTodoId: parentRecurringTodoId,
                #locationLatitude: locationLatitude,
                #locationLongitude: locationLongitude,
                #locationName: locationName,
                #locationRadius: locationRadius,
              },
            ),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, int>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, int>>(
                this,
                Invocation.method(
                  #createTodo,
                  [title, description, dueDate],
                  {
                    #categoryId: categoryId,
                    #notificationTime: notificationTime,
                    #recurrenceRule: recurrenceRule,
                    #parentRecurringTodoId: parentRecurringTodoId,
                    #locationLatitude: locationLatitude,
                    #locationLongitude: locationLongitude,
                    #locationName: locationName,
                    #locationRadius: locationRadius,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, int>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> updateTodo(_i7.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
                this,
                Invocation.method(#updateTodo, [todo]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> toggleCompletion(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCompletion, [id]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
                this,
                Invocation.method(#toggleCompletion, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, int>> deleteCompletedTodos() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCompletedTodos, []),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, int>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, int>>(
                this,
                Invocation.method(#deleteCompletedTodos, []),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, int>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> scheduleNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledDate: scheduledDate,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> areNotificationsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#areNotificationsEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> openNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openNotificationSettings, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i10.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, []),
            returnValue:
                _i4.Future<List<_i10.PendingNotificationRequest>>.value(
                  <_i10.PendingNotificationRequest>[],
                ),
          )
          as _i4.Future<List<_i10.PendingNotificationRequest>>);

  @override
  _i4.Future<bool> canScheduleExactAlarms() =>
      (super.noSuchMethod(
            Invocation.method(#canScheduleExactAlarms, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> openExactAlarmSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openExactAlarmSettings, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> snoozeNotification({
    required int? id,
    required String? title,
    required String? body,
    required Duration? snoozeDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#snoozeNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #snoozeDuration: snoozeDuration,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> showLocationNotification({
    required int? id,
    required String? title,
    required String? body,
    required double? distance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showLocationNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #distance: distance,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RecurringTodoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringTodoService extends _i1.Mock
    implements _i11.RecurringTodoService {
  MockRecurringTodoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTodoRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TodoRepository);

  @override
  _i3.Clock get clock =>
      (super.noSuchMethod(
            Invocation.getter(#clock),
            returnValue: _FakeClock_1(this, Invocation.getter(#clock)),
          )
          as _i3.Clock);

  @override
  _i4.Future<void> generateUpcomingInstances({int? lookAheadDays = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#generateUpcomingInstances, [], {
              #lookAheadDays: lookAheadDays,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> generateInstancesForNewMaster(_i7.Todo? masterTodo) =>
      (super.noSuchMethod(
            Invocation.method(#generateInstancesForNewMaster, [masterTodo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
